# Makefile

BINDIR=~/.mwg

.PHONY: all
all: $(BINDIR)/modls.exe

$(BINDIR):
	test -d $(BINDIR) || mkdir $(BINDIR)

$(BINDIR)/modls.exe: modls.cpp scanner.h colored_string.h $(BINDIR)
	g++ modls.cpp -o$@
